name: CI for Orion HTTP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build the project
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build the project
        run: cargo build --release

      - name: Publish binary
        uses: actions/upload-artifact@v3
        with:
          name: orion_http
          path: target/release/orion_http
