[package]
name = "app-wasm-pack"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.10"
fastrand = "*" 
getrandom = { version = "*", features = ["js"] }

[dependencies.web-sys]
version = "0.3.77"
features = ["Window"]
