[package]
name = "rest_client"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl-sys = "0.9.104"
reqwest = { version = "0.12.9", features = ["blocking"] }

[lib]
name = "rest_client"
crate-type = ["cdylib"]

